apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  # .dockerconfigjson: ewoJImF1dGhzIjogeJCQkiYXV0aCI6ICJaR0W10aFVXbFZSbTVaKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
  .dockerconfigjson: ew0gICJhdXRocyI6IHsNICAgICJnaGNyLmlvIjogew0gICAgICAidXNlcm5hbWUiOiAiYmlub20xOTgyIiwNICAgICAgInBhc3N3b3JkIjogImdocF9Cb3BBdmxkYlpHNk5WZDlJZWdsYXg3Ym1XNEdTRnYzREgwWXEiLA0gICAgICAiYXV0aCI6ICJZbWx1YjIweE9UZ3lPbWRvY0Y5Q2IzQkJkbXhrWWxwSE5rNVdaRGxKWldkc1lYZzNZbTFYTkVkVFJuWXpSRWd3V1hFPSINICAgIH0NICB9DX0=
type: kubernetes.io/dockerconfigjson
